apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: ${IP_ADDRESS}
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: "${KUBERNETES_VERSION}.0"
controlPlaneEndpoint: "${ENDPOINT_NAME}:6443"
networking:
  podSubnet: ${POD_SUBNET}
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
# Enable containerd runtime
cgroupDriver: "systemd"
containerRuntimeEndpoint: "unix:///run/containerd/containerd.sock"